/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctOption' : IDL.Nat,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'subjectId' : IDL.Nat,
  'questions' : IDL.Vec(Question),
});
export const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Answer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});
export const DetailedResult = IDL.Record({
  'correctOption' : IDL.Nat,
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'detailedResults' : IDL.Vec(DetailedResult),
  'incorrectCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'percentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getSubjectQuizzes' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(Answer)], [QuizResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctOption' : IDL.Nat,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'subjectId' : IDL.Nat,
    'questions' : IDL.Vec(Question),
  });
  const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Answer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  const DetailedResult = IDL.Record({
    'correctOption' : IDL.Nat,
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'detailedResults' : IDL.Vec(DetailedResult),
    'incorrectCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getSubjectQuizzes' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitQuizAnswers' : IDL.Func(
        [IDL.Nat, IDL.Vec(Answer)],
        [QuizResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };