/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : bigint, 'selectedOption' : bigint }
export interface DetailedResult {
  'correctOption' : bigint,
  'isCorrect' : boolean,
  'questionId' : bigint,
  'selectedOption' : bigint,
}
export interface Question {
  'id' : bigint,
  'correctOption' : bigint,
  'questionText' : string,
  'options' : Array<string>,
}
export interface Quiz {
  'id' : bigint,
  'name' : string,
  'subjectId' : bigint,
  'questions' : Array<Question>,
}
export interface QuizResult {
  'detailedResults' : Array<DetailedResult>,
  'incorrectCount' : bigint,
  'correctCount' : bigint,
  'percentage' : number,
}
export interface Subject { 'id' : bigint, 'name' : string }
export interface _SERVICE {
  'getQuizQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getSubjectQuizzes' : ActorMethod<[bigint], Array<Quiz>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitQuizAnswers' : ActorMethod<[bigint, Array<Answer>], QuizResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];